[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:code-server]
command=code-server --bind-addr 0.0.0.0:8080 --auth none --disable-telemetry --disable-update-check --extensions-dir /opt/code-server/extensions /workspace
environment=HOME="/home/node"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:express-build]
directory=/workspace/build/server
command=/opt/modules/build/server/node_modules/.bin/nodemon app.js
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:vite-build]
directory=/workspace/build/client
command=/opt/modules/build/client/node_modules/.bin/vite
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
